name: Notificar a ntfy.sh al hacer push a main

on:
  push:
    branches:
      - main

jobs:
  notificar:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificación a ntfy.sh
        run: |
          curl -H "Title: 🚀 Push detectado en main" \
               -H "Priority: high" \
               -d "Se ha subido nuevo código al repositorio en la rama main." \
               https://ntfy.sh/devops-itla
